name = "Project"
uuid = "5c896461-b006-4c80-bebf-30164a083543"
authors = ["Yingtao-Hu <z5463327@ad.unsw.edu.au> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
